@echo off
echo Stopping all RevCart services...

echo Stopping Angular frontend (port 4200)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":4200" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping API Gateway (port 8080)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8080" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Auth Service (port 8081)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8081" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping User Service (port 8082)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8082" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Product Service (port 8083)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8083" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Cart Service (port 8084)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8084" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Order Service (port 8085)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8085" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Payment Service (port 8086)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8086" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Notification Service (port 8087)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8087" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Delivery Service (port 8088)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8088" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Analytics Service (port 8089)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8089" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Admin Service (port 8090)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8090" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo Stopping Consul (port 8500)...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8500" ^| find "LISTENING"') do taskkill /F /PID %%a 2>nul

echo.
echo All services stopped!
pause
