@echo off
echo Starting All Microservices...

echo Building all services...
call mvn clean install -DskipTests

echo Starting API Gateway...
start "API Gateway" cmd /k "cd api-gateway && mvn spring-boot:run"

echo Starting User Service...
start "User Service" cmd /k "cd user-service && mvn spring-boot:run"

echo Starting Product Service...
start "Product Service" cmd /k "cd product-service && mvn spring-boot:run"

echo Starting Cart Service...
start "Cart Service" cmd /k "cd cart-service && mvn spring-boot:run"

echo Starting Order Service...
start "Order Service" cmd /k "cd order-service && mvn spring-boot:run"

echo Starting Payment Service...
start "Payment Service" cmd /k "cd payment-service && mvn spring-boot:run"

echo Starting Notification Service...
start "Notification Service" cmd /k "cd notification-service && mvn spring-boot:run"

echo Starting Delivery Service...
start "Delivery Service" cmd /k "cd delivery-service && mvn spring-boot:run"

echo Starting Analytics Service...
start "Analytics Service" cmd /k "cd analytics-service && mvn spring-boot:run"

echo All microservices are starting...
echo Check individual windows for startup status.

pause